export const topicAction = {
  GET_TOPICS: 'GET_TOPICS',
  GET_TOPICS_SUCCESS: 'GET_TOPICS_SUCCESS',
  GET_TOPIC_DETAIL: 'GET_TOPIC_DETAIL',
  GET_TOPIC_DETAIL_SUCCESS: 'GET_TOPIC_DETAIL_SUCCESS'
}

export const commentAction = {
  GET_COMMENTS: 'GET_COMMENTS',
  GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
  GET_COMMENT_DETAIL: 'GET_COMMENT_DETAIL',
  GET_COMMENT_DETAIL_SUCCESS: 'GET_COMMENT_DETAIL_SUCCESS'
}

export const userAction = {
  LOG_IN: 'LOG_IN',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  SIGN_UP: 'SIGN_UP',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  GET_USERS: 'GET_USERS',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS'
}