export const topicAction = {
  GET_TOPICS: 'GET_TOPICS',
  GET_TOPICS_SUCCESS: 'GET_TOPICS_SUCCESS',
  GET_TOPIC_DETAIL: 'GET_TOPIC_DETAIL',
  GET_TOPIC_DETAIL_SUCCESS: 'GET_TOPIC_DETAIL_SUCCESS'
}

export const userAction ={
  GET_USERS: 'GET_USERS',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS'
}